-- SMK Pruebas de Humo - DDL tablas (MariaDB/MySQL, BD de negocio jdbc/Appian)
-- Generado desde los record types de DEV. Solo necesario si el import del paquete no crea las tablas.

CREATE TABLE IF NOT EXISTS SMK_TEST (
  ID INT NOT NULL AUTO_INCREMENT,
  CODIGO VARCHAR(255) NULL,
  NOMBRE VARCHAR(255) NULL,
  CATEGORIA VARCHAR(255) NULL,
  SISTEMA VARCHAR(255) NULL,
  DESCRIPCION VARCHAR(4000) NULL,
  CRITICIDAD VARCHAR(255) NULL,
  ACTIVO BOOLEAN NULL,
  MOTIVO_INACTIVO VARCHAR(255) NULL,
  ORIGEN_ALTA VARCHAR(255) NULL,
  ORDEN INT NULL,
  UMBRAL_MS INT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY UK_SMK_TEST_CODIGO (CODIGO)
);

CREATE TABLE IF NOT EXISTS SMK_EJECUCION (
  ID INT NOT NULL AUTO_INCREMENT,
  FECHA_INICIO DATETIME NULL,
  FECHA_FIN DATETIME NULL,
  ESTADO VARCHAR(255) NULL,
  ORIGEN VARCHAR(255) NULL,
  MOTIVO VARCHAR(4000) NULL,
  LANZADO_POR VARCHAR(255) NULL,
  TOTAL_PRUEBAS INT NULL,
  TOTAL_OK INT NULL,
  TOTAL_KO INT NULL,
  TOTAL_WARN INT NULL,
  DURACION_MS INT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SMK_RESULTADO (
  ID INT NOT NULL AUTO_INCREMENT,
  EJECUCION_ID INT NULL,
  TEST_CODIGO VARCHAR(255) NULL,
  TEST_NOMBRE VARCHAR(255) NULL,
  CATEGORIA VARCHAR(255) NULL,
  SISTEMA VARCHAR(255) NULL,
  RESULTADO VARCHAR(255) NULL,
  MENSAJE VARCHAR(4000) NULL,
  DETALLE TEXT NULL,
  DURACION_MS INT NULL,
  FECHA_INICIO DATETIME NULL,
  FECHA_FIN DATETIME NULL,
  PRIMARY KEY (ID)
);

CREATE INDEX IX_SMK_RESULTADO_EJEC ON SMK_RESULTADO (EJECUCION_ID);