# Generated by Django 5.2.17 on 2026-10-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    # initial: permite `migrate --fake-initial` si Liquibase (002-tva-configuracion.sql) ya creó la tabla.
    initial = True

    dependencies = [
        ("tva", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionIntegracion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=64, unique=True)),
                ("valor", models.TextField(blank=True, default="")),
                ("secreto", models.BooleanField(default=False)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("actualizado_por", models.CharField(blank=True, default="", max_length=128)),
            ],
            options={
                "db_table": "tva_configuracion",
            },
        ),
    ]
